spring:
  application:
    name: soap-web-service-17

service:
  security:
    keystore:
      location: keystore/emsnewkeystore.jks
      alias: emsnewcert
      password: emsnewpassword
      private-key-password: emsnewpassword
    interceptor:
      is-debug-mode: true
